psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_DATABASE" <<-EOSQL
CREATE TYPE public.baselines_genre_enum AS ENUM ('M', 'F'); ALTER TYPE public.baselines_genre_enum OWNER TO postgres;
CREATE TYPE public.baselines_race_enum AS ENUM ('M', 'B', 'W'); ALTER TYPE public.baselines_race_enum OWNER TO postgres;

CREATE TABLE public.roles ( id uuid NOT NULL DEFAULT uuid_generate_v4(), name character varying COLLATE pg_catalog."default" NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY (id) ); ALTER TABLE public.roles OWNER to postgres;
CREATE TABLE public.users ( id uuid NOT NULL DEFAULT uuid_generate_v4(), name character varying COLLATE pg_catalog."default" NOT NULL, username character varying COLLATE pg_catalog."default" NOT NULL, password character varying COLLATE pg_catalog."default" NOT NULL, email character varying COLLATE pg_catalog."default" NOT NULL, phone character varying COLLATE pg_catalog."default" NOT NULL, cpf character varying COLLATE pg_catalog."default" NOT NULL, "roleId" uuid NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY (id), CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES public.roles (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION ); ALTER TABLE public.users OWNER to postgres;
CREATE TABLE public.baselines ( id uuid NOT NULL DEFAULT uuid_generate_v4(), age integer NOT NULL, genre baselines_genre_enum NOT NULL, race baselines_race_enum NOT NULL, weight numeric NOT NULL, height numeric NOT NULL, city boolean NOT NULL, recent_appointments boolean NOT NULL, contact_covid19 boolean NOT NULL, mask boolean NOT NULL, occupation character varying COLLATE pg_catalog."default" NOT NULL, occupation_local character varying COLLATE pg_catalog."default" NOT NULL, hypertension boolean NOT NULL, diabetes boolean NOT NULL, heart_disease boolean NOT NULL, lung_disease boolean NOT NULL, asthma boolean NOT NULL, smoking boolean NOT NULL, kidney_disease boolean NOT NULL, cancer boolean NOT NULL, corticosteroids_or_methotrexate boolean NOT NULL, gestation boolean NOT NULL, "userId" uuid NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_6177fb1b69ff49ab766da9e3c7f" PRIMARY KEY (id), CONSTRAINT "REL_547d33f13e2d1f98976bbc6e03" UNIQUE ("userId"), CONSTRAINT "FK_547d33f13e2d1f98976bbc6e03b" FOREIGN KEY ("userId") REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION ); ALTER TABLE public.baselines OWNER to postgres;
CREATE TABLE public.diaries ( id uuid NOT NULL DEFAULT uuid_generate_v4(), "smellLoss" boolean NOT NULL, "tasteLoss" boolean NOT NULL, "appetiteLoss" boolean NOT NULL, fatigue boolean NOT NULL, fever boolean NOT NULL, cough boolean NOT NULL, diarrhea boolean NOT NULL, delirium boolean NOT NULL, "soreThroat" boolean NOT NULL, "shortnessOfBreath" boolean NOT NULL, "abdominalPain" boolean NOT NULL, "chestPain" boolean NOT NULL, approved boolean NOT NULL, "userId" uuid NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_ffd738e7d40dcfa59283dcaae87" PRIMARY KEY (id), CONSTRAINT "FK_6454969d8c037fee60374c8527c" FOREIGN KEY ("userId") REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION ); ALTER TABLE public.diaries OWNER to postgres;
CREATE TABLE public.establishments ( id uuid NOT NULL DEFAULT uuid_generate_v4(), name character varying COLLATE pg_catalog."default" NOT NULL, email character varying COLLATE pg_catalog."default" NOT NULL, cnpj character varying COLLATE pg_catalog."default" NOT NULL, phone character varying COLLATE pg_catalog."default" NOT NULL, city character varying COLLATE pg_catalog."default" NOT NULL, active boolean NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_7fb6da6c365114ccb61b091bbdf" PRIMARY KEY (id) ); ALTER TABLE public.establishments OWNER to postgres;
CREATE TABLE public.resources ( id uuid NOT NULL DEFAULT uuid_generate_v4(), name character varying COLLATE pg_catalog."default" NOT NULL, "to" character varying COLLATE pg_catalog."default" NOT NULL, icon character varying COLLATE pg_catalog."default" NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_632484ab9dff41bba94f9b7c85e" PRIMARY KEY (id) ); ALTER TABLE public.resources OWNER to postgres;
CREATE TABLE public.roles_resources ( "rolesId" uuid NOT NULL, "resourcesId" uuid NOT NULL, CONSTRAINT "PK_6f150c547e2e7214cffe8dbd9e4" PRIMARY KEY ("rolesId", "resourcesId"), CONSTRAINT "FK_4b524f90163dedb1c8beb4914ac" FOREIGN KEY ("resourcesId") REFERENCES public.resources (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "FK_d8b394f8480c23ef5ddde9607fe" FOREIGN KEY ("rolesId") REFERENCES public.roles (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE ); ALTER TABLE public.roles_resources OWNER to postgres;
CREATE TABLE public.statistic_types ( id uuid NOT NULL DEFAULT uuid_generate_v4(), name character varying COLLATE pg_catalog."default" NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_b0df9f8ecd1884efe9de6dff57c" PRIMARY KEY (id) ); ALTER TABLE public.statistic_types OWNER to postgres;
CREATE TABLE public.statistics ( id uuid NOT NULL DEFAULT uuid_generate_v4(), value numeric NOT NULL, "statisticTypeId" uuid NOT NULL, "establishmentId" uuid NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_c3769cca342381fa827a0f246a7" PRIMARY KEY (id), CONSTRAINT "FK_69b4ea3e8f6deac0fc4dc6a9e78" FOREIGN KEY ("statisticTypeId") REFERENCES public.statistic_types (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "FK_9147df80cc822ce1e4b0db81cc7" FOREIGN KEY ("establishmentId") REFERENCES public.establishments (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION ); ALTER TABLE public.statistics OWNER to postgres;
CREATE TABLE public.tokens ( id uuid NOT NULL DEFAULT uuid_generate_v4(), token uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY (id), CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2" FOREIGN KEY ("userId") REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION ); ALTER TABLE public.tokens OWNER to postgres;
CREATE TABLE public.users_establishments ( "usersId" uuid NOT NULL, "establishmentsId" uuid NOT NULL, CONSTRAINT "PK_fa49abe51e3d27b550820f37ad8" PRIMARY KEY ("usersId", "establishmentsId"), CONSTRAINT "FK_5e91740c2938a9da00058304db8" FOREIGN KEY ("establishmentsId") REFERENCES public.establishments (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "FK_63dea19e6502a5f53c75df8af9e" FOREIGN KEY ("usersId") REFERENCES public.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE ); ALTER TABLE public.users_establishments OWNER to postgres;
EOSQL
