cd /initdb

mongo --eval "var SCHEDULE_USER='$SCHEDULE_USER'; var SCHEDULE_PASS='$SCHEDULE_PASS'; var MONGO_USER='$MONGO_INITDB_ROOT_USERNAME'; var MONGO_PASS='$MONGO_INITDB_ROOT_PASSWORD';" database.js

