cd /initdb

mongo --eval "var SCHEDULE_USER='$SCHEDULE_USER'; var SCHEDULE_PASS='$SCHEDULE_PASS'; var MONGO_INITDB_ROOT_USERNAME='$MONGO_INITDB_ROOT_USERNAME'; var MONGO_INITDB_ROOT_PASSWORD='$MONGO_INITDB_ROOT_PASSWORD';" database.js

